logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/market
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    show_sql: true
app:
  image:
    bucket: /Users/nazar/IdeaProjects/Market/images